<?php
namespace gamboamartin\gastos\models;
use base\orm\_modelo_parent_sin_codigo;
use base\orm\modelo;
use gamboamartin\errores\errores;
use gamboamartin\system\_ctl_parent_sin_codigo;
use PDO;
use stdClass;

class gt_solicitud extends _modelo_parent_sin_codigo {
    public function __construct(PDO $link){
        $tabla = 'gt_solicitud';
        $columnas = array($tabla=>false,'gt_tipo_solicitud'=>$tabla,'gt_centro_costo'=>$tabla,
            'gt_tipo_centro_costo'=>'gt_centro_costo');
        $campos_obligatorios = array();

        $no_duplicados = array();


        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas,no_duplicados: $no_duplicados);

        $this->NAMESPACE = __NAMESPACE__;
    }

    public function alta_bd(array $keys_integra_ds = array('descripcion')): array|stdClass
    {
        if(!isset($this->registro['codigo']))
            $this->registro['codigo'] = $this->registro['gt_centro_costo_id'].'.'.$this->registro['gt_tipo_solicitud_id'].'.'.rand();
        if(!isset($this->registro['descripcion_select']))
            $this->registro['descripcion_select'] = strtoupper($this->registro['descripcion']). ' ' .$this->registro['gt_centro_costo_id'].' '.$this->registro['gt_tipo_solicitud_id'];
        if(!isset($this->registro['alias']))
            $this->registro['alias'] = $this->registro['descripcion_select'];
        if(!isset($this->registro['codigo_bis']))
            $this->registro['codigo_bis'] = $this->registro['codigo'];

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds);
        if(errores::$error){
            return $this->error->error('Error al dar de alta registro',$r_alta_bd);
        }

        return $r_alta_bd;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false, array $keys_integra_ds = array('descripcion')): array|stdClass
    {
        if(!isset($registro['codigo'])){
            if($registro['gt_centro_costo_id'] != $this->registros[0]['gt_solicitud_gt_centro_costo_id'] || $registro['gt_tipo_solicitud_id'] != $this->registros[0]['gt_solicitud_gt_tipo_solicitud_id'])
                $registro['codigo'] = $registro['gt_centro_costo_id'].'.'.$registro['gt_tipo_solicitud_id'].'.'.rand();
        }
        if(!isset($registro['descripcion_select']))
            $registro['descripcion_select'] = strtoupper($registro['descripcion']). ' ' .$registro['gt_centro_costo_id'].' '.$registro['gt_tipo_solicitud_id'];
        if(!isset($registro['alias']))
            $registro['alias'] = $registro['descripcion_select'];
        if(!isset($this->registro['codigo_bis']))
            if($registro['gt_centro_costo_id'] != $this->registros[0]['gt_solicitud_gt_centro_costo_id'] || $registro['gt_tipo_solicitud_id'] != $this->registros[0]['gt_solicitud_gt_tipo_solicitud_id'])
                $registro['codigo_bis'] = $registro['codigo'];

        $r_modifica_bd = parent::modifica_bd($registro, $id, $reactiva, $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error('Error al modificar registro',$r_modifica_bd);
        }

        return $r_modifica_bd;
    }


}