<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\gastos\controllers;

use config\generales;
use gamboamartin\errores\errores;
use gamboamartin\system\links_menu;
use gamboamartin\system\system;
use gamboamartin\template\html;
use html\gt_solicitante_html;
use html\gt_tipo_solicitud_html;
use models\gt_solicitante;
use models\gt_tipo_solicitud;
use PDO;
use stdClass;

class controlador_gt_solicitante extends system {



    public function __construct(PDO $link, stdClass $paths_conf = new stdClass()){
        $modelo = new gt_solicitante(link: $link);
        $html_base = new html();
        $html = new gt_solicitante_html(html: $html_base);
        $obj_link = new links_menu($this->registro_id);
        $this->rows_lista[] = 'gt_tipo_solicitud_id';

        parent::__construct(html:$html, link: $link,modelo:  $modelo, obj_link: $obj_link, paths_conf: $paths_conf);

        $this->titulo_lista = 'Solicitante';

    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta = parent::alta(header: false, ws: false); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al generar template', data: $r_alta, header: $header, ws: $ws);
        }

        $select = (new gt_tipo_solicitud_html(html: $this->html_base))->select_gt_tipo_solicitud_id(cols:12,con_registros: true,
            id_selected: -1, link: $this->link);
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al generar select', data: $select);
            print_r($error);
            die('Error');
        }
        $this->inputs->select = new stdClass();

        $this->inputs->select->gt_tipo_solicitud_id= $select;

        return $r_alta;

    }

}